platform :ios, '9.0'
use_frameworks!
def pods
pod 'RDVTabBarController','~>1.1.9'
pod 'AFNetworking','~>3.1'
pod 'SDWebImage','~>3.8.1'
pod 'MJRefresh','~>3.1.7'
pod 'YYModel','~>1.0.4'
pod 'IQKeyboardManager'
end
target 'Mr.Time' do
 pods
end
